/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 5.7.4
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2023 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
(function(b){function n(a){a.preventDefault();a=b(this);a.hasClass("option-less")&&(b(".faqSearchControl.option-more").removeClass("h-hide"),b(".faqSearchFields").addClass("h-hide"));a.hasClass("option-more")&&(a.addClass("h-hide"),b(".faqSearchFields").removeClass("h-hide"))}function k(a){var c=b(".faq-content .faq-answer");b(".faq-group-title",c).html(a.title);b(".faq-group-body",c).html(a.text);b(".faq-groups .faq-link.selected").removeClass("selected");b(".faq-groups .faq-link").each(function(){var c=
b(this);if(c.data("group")==a.faqparent&&c.data("item")==a.faqname)return c.addClass("selected"),b(".js-rx-help-menu-select").selectBox("value",c.data("path")),!1});l(c)}function l(a){var c=b(".js-faq-search-query").data("highlight");c&&b(c.split(",")).each(function(c,f){b(".faq-group-body",a).highlight(f)})}function p(a){a.preventDefault();var c=b(this).data("group"),d=b(this).data("item");window.location.hash=b(this).data("path");e[c]&&e[c][d]?k(e[c][d]):vBulletin.AJAX({url:vBulletin.getAjaxBaseurl()+
"/ajax/api/help/getAnswers",data:{group:c},success:function(a,b,h){a.answers?(e[c]=a.answers,e[c][d]?k(e[c][d]):console.log("can't load help for "+c+"/"+d)):console.log("can't load help for "+c)}})}function h(a){b(".faq-groups a").each(function(){var c=b(this);if(c.data("path")==a){for(var d=c,f,g=!1,e=100;--e;)if(d=d.parent().closest(".faq-group"),f=d.find("> .faq-group-title"),1==f.length)g=f;else break;g&&1==g.length&&(d=b(".faq-groups"),f=b(".faqs"),d.removeClass("h-hide-on-small"),f.css("width",
"220px"),g.trigger("click"),d.addClass("h-hide-on-small"),f.css("width",""));c.is(".faq-link")||c.parent().find(".faq-link").first().trigger("click");c.trigger("click");return!1}})}function q(a){a=b(a.target).attr("href");if("help#"==a.substr(0,5))return a=a.substr(5),h(a),!1}function m(a,c,d){a.find("> li.faq-group, > li").each(function(){var a=b(this),e=a.find("> .faq-group-title, > .faq-link");b("<option />").prop("value",e.data("path")).text(c+" "+e.text()).appendTo(d);a=a.find("> .sub-faqs > .faq-group-body");
0<a.length&&m(a,c+"---",d)})}function r(a){a=a.target;a=b(a[a.selectedIndex]).val();h(a)}var e={};b(function(){b(".faqSearchControl").off("click").on("click",n);b(".help-widget").off("click",".faq-link").on("click",".faq-link",p);b(".help-widget").off("click",".faq-content a").on("click",".faq-content a",q);b(".faqs ul.acc").accordion({heightStyle:"content",icons:{activeHeader:"js-help-icon h-center-vertical h-margin-right-s b-icon b-icon__arrow-down-s",header:"js-help-icon h-center-vertical h-margin-right-s b-icon b-icon__arrow-right-s"}});
b(".js-help-icon").removeClass("ui-icon").parent().addClass("h-center-vertical-container");if(window.location.hash){var a=window.location.hash.substr(1);h(a)}l(b(".faq-content .faq-answer"));a=b(".faq-groups");var c=b("<select />").addClass("js-rx-help-menu-select");m(a,"",c);var d=b("<div />").addClass("rx-help-menu h-hide-on-large").append(c).insertAfter(a);c.off("change").on("change",r);a.addClass("h-hide-on-small");d.removeClass("h-hide-on-large");c.selectBox();d.addClass("h-hide-on-large")})})(jQuery);
