/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 5.7.4
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2023 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("cancel delete_posts delete_thread inline_moved inlinemod_auth inlinemod_auth_password_empty loading login manage_content manage_deleted merge_posts merge_threads_ginlinemod move_posts move_threads_ginlinemod not_much_would_be_accomplished_by_merging options please_select_at_least_one_post please_select_at_least_two_posts remove_redirects this_post_has_been_successfully_approved this_post_has_been_successfully_unapproved this_topic_has_been_stuck this_topic_has_been_successfully_approved this_topic_has_been_successfully_opened this_topic_has_been_successfully_unapproved this_topic_has_been_successfully_unstuck this_topic_is_closed this_topic_is_deleted this_topic_is_undeleted thread_redirects_removed unapproved you_did_not_select_any_valid_threads".split(" "),
[]);
(function(a){function t(c,d){return new Promise((e,b)=>{vBulletin.dialogtools.openTemplateConfirmDialog(vBulletin.ajaxtools,{title:"spam_management",width:500,dialogClass:"inlinemod-spam-dialog",yesPhrase:"proceed_ellipsis",noPhrase:"cancel",onClickYes:b=>{b=b.find(".spam-form");d.userids=[];b.find(":input[name='userids[]']:checked").each(function(){d.userids.push(a(this).val())});d.banusergroupid=b.find(":input[name=usergroupid]").val();d.period=b.find(":input[name=period]").val();d.banreason=b.find(":input[name=banreason]").val();
d.report=c.find(":input[name=report]").is(":checked")?1:0;vBulletin.AJAX({url:vBulletin.normalizeAjaxUrl(b.attr("action")),cpaction:!0,data:d,title_phrase:"spam_management",error_phrase:"error_deleting_posts",success:function(a){e({response:a,postData:d})}})}},{name:"inlinemod_delete_spam",data:{nodeIds:d.nodeids,banusers:d.banusers}}).then(c=>{c.find(".spam-form").offon("submit",a=>{a.preventDefault()});a("select",c).selectBox()})})}function u(c,d,e){e||(e="approve");var b=m(a(c)),f=e+"_threads",
h="approve"==e?1:0;classes="unapproved";itemSelector=".list-item";statusPrefix="this_topic_has_been_successfully_";d&&(classes+=" b-post--unapproved",itemSelector=".js-post",statusPrefix="this_post_has_been_successfully_");if(0==b.length)n(f);else return vBulletin.AJAX({call:"/ajax/api/node/setApproved",cpaction:!0,data:{nodeids:b,approved:h},title_phrase:f,error_phrase:"error_un_approving_topics",allowEmptyResponse:!0,success:function(b){vBulletin.inlinemod.clear.apply(c);b?"thread"==l?(-1!=a.inArray(a(c).attr("data-node-id"),
b)&&a(".canvas-widget").toggleClass("unapproved",h),a(".inlinemod-item .cb_inlinemod",g).each(function(){-1!=a.inArray(this.value,b)&&(a(this).closest(itemSelector).toggleClass(classes,h),h?a(this).prev(".js-unapprove-label").remove():a('<span class="js-unapprove-label b-post__inlinemod-text">{0}</span>'.format(vBulletin.phrase.get("unapproved"))).insertBefore(this))}),showStatusMessage(vBulletin.phrase.get(statusPrefix+(h?"approved":"unapproved")),"approve")):v(c):vBulletin.warning(f,"nothing_to_do")}}),
!1}function v(c){(c=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof c.applyFilters&&c.forceApplyFilters()}function w(c){(c.is(".inlinemod-item")?c:c.find(".inlinemod-item")).each(function(){var c=a(this);if(c.find(".js-photo-preview").length||c.find(".js-post-attachments").length)c.addClass("im-attach");else for(var e=a(".js-post__content-text",this),b=["img","iframe.restrain"],f=0;f<b.length;f++){var h=a(b[f],e).length,q=a(".bbcode_container "+
b[f],e).length;if(0<h&&h!=q){c.addClass("im-attach");break}}})}function n(a){vBulletin.warning(a,"please_select_at_least_one_post")}function m(a){return(a=a.attr("data-node-id"))?[a]:p()}function p(){var c=a.cookie(k),d=[];c&&(d=c.split(","));return d}vBulletin.ensureObj("inlinemod");vBulletin.inlinemod.delete_form_thread=function(){var c=this,d=m(a(c));0==d.length?n("delete_thread"):vBulletin.dialogtools.openTemplateConfirmDialog(vBulletin.ajaxtools,{title:"delete_thread",width:500,dialogClass:"no-buttons-while-loading",
yesPhrase:"delete_thread",noPhrase:"cancel",onClickYes:function(e){var b=e.find(".delete-posts-form"),f=b.find("input:radio[name=deletetype]:checked").val()||1,h={hard:2==f?1:0,reason:b.find(":input[name=deletereason]").val(),nodeids:d,deleteother:b.find(":input[name=deleteother]").is(":checked")?1:0,report:b.find(":input[name=report]").is(":checked")?1:0,banusers:"ban"==b.find("input:radio[name=useraction]:checked").val()?1:0};h.deleteother||h.banusers||h.report?setTimeout(()=>{t(b,h).then(b=>{a.cookie(k,
null,{path:pageData.cookie_path,domain:pageData.cookie_domain});"thread"==l&&2==f?location.replace(a("#breadcrumbs .crumb a:last").attr("href")):(b=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof b.applyFilters?b.forceApplyFilters():location.reload()})},500):vBulletin.AJAX({url:vBulletin.normalizeAjaxUrl(b.attr("action")),cpaction:!0,data:h,title_phrase:"delete_thread",error_phrase:"error_deleting_posts",success:function(b){a.cookie(k,null,{path:pageData.cookie_path,
domain:pageData.cookie_domain});if("thread"==l&&2==f)-1!=a.inArray(a(c).attr("data-node-id"),b)||-1!=a.inArray(pageData.nodeid,b)?location.replace(a("#breadcrumbs .crumb a:last").attr("href")):a("input.cb_inlinemod[type=checkbox]:checked",g).each(function(){-1!=a.inArray(a(this).val(),b)&&a(this).parents(".inlinemod-item").remove()});else{-1!=a.inArray(a(c).attr("data-node-id"),b)&&a(".conversation-content-widget").addClass("deleted");var d=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance");
d&&"function"==typeof d.applyFilters?d.forceApplyFilters():location.reload()}}})}},{name:"inlinemod_delete_form",data:{postcount:d.length,nodeids:d,deleteposts:1,removeposts:1,firstpost:1}}).then(c=>{a("select",c).selectBox()})};vBulletin.inlinemod.delete_dialog=function(c,d){vBulletin.dialogtools.openTemplateConfirmDialog(vBulletin.ajaxtools,{title:"delete_posts",width:500,dialogClass:"no-buttons-while-loading",yesPhrase:"delete_posts",noPhrase:"cancel",onClickYes:a=>{var b=a.find(".delete-posts-form"),
e={hard:2==(b.find("input:radio[name=deletetype]:checked").val()||1)?1:0,reason:b.find(":input[name=deletereason]").val(),nodeids:c,deleteother:b.find(":input[name=deleteother]").is(":checked")?1:0,report:b.find(":input[name=report]").is(":checked")?1:0,banusers:"ban"==b.find("input:radio[name=useraction]:checked").val()?1:0};e.deleteother||e.banusers||e.report?setTimeout(()=>{t(b,e).then(a=>{vBulletin.ensureFun(d)(a.response,a.postData);vBulletin.inlinemod.clear()})},500):vBulletin.AJAX({url:vBulletin.normalizeAjaxUrl(b.attr("action")),
cpaction:!0,data:e,title_phrase:"delete_posts",error_phrase:"error_deleting_posts",success:a=>{vBulletin.ensureFun(d)(a,e);vBulletin.inlinemod.clear()}})}},{name:"inlinemod_delete_form",data:{postcount:c.length,nodeids:c,deleteposts:1,removeposts:1,firstpost:1}}).then(c=>{a("select",c).selectBox()})};vBulletin.inlinemod.delete_form=function(){var c=a(this),d=m(c);0==d.length?n("delete_posts"):vBulletin.inlinemod.delete_dialog(d,function(d,b){if(b.nodeids&&a.isArray(b.nodeids)){var e=!1;a.each(b.nodeids,
function(c,b){-1==a.inArray(b,d)&&(e=!0)});e&&vBulletin.warning("delete_posts","error_deleting_one_or_more_posts")}a.cookie(k,null,{path:pageData.cookie_path,domain:pageData.cookie_domain});l&&"thread"==l&&1==b.hard?!c||-1==a.inArray(c.attr("data-node-id"),d)&&-1==a.inArray(pageData.nodeid,d)?a("input.cb_inlinemod[type=checkbox]:checked",g).each(function(){-1!=a.inArray(a(this).val(),d)&&a(this).closest(".inlinemod-item").remove()}):location.replace(a("#breadcrumbs .crumb a:last").attr("href")):(b=
a(".filter-wrapper",c.parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof b.applyFilters?b.forceApplyFilters():location.reload()})};vBulletin.inlinemod.moveThreads=function(){var c=m(a(this));movephrase="move_threads_ginlinemod";movephraserendered=vBulletin.phrase.get(movephrase);if(0==c.length)n(movephrase);else{var d=openConfirmDialog({title:movephraserendered,message:vBulletin.phrase.get("loading")+"...",width:500,dialogClass:"inlinemod-move-dialog loading",buttonLabel:{yesLabel:movephraserendered,
noLabel:vBulletin.phrase.get("cancel")},onClickYes:function(){var e=d.find(".move-posts-form"),b={};e.find("input[name=enableredirect]").prop("checked")&&(b.redirect=e.find("#rb_redirect_perm").prop("checked")?"perm":"expires","expires"==b.redirect&&(b.period=e.find("select[name=period]").val(),b.frame=e.find("select[name=frame]").val()),console.log("Redirect data compiled:"),console.dir(b));b={to_parent:e.find("select[name=destchannelid]").val(),nodeids:c,leaveRedirectData:b};vBulletin.AJAX({url:vBulletin.normalizeAjaxUrl(e.attr("action")),
cpaction:!0,data:b,type:e.attr("method"),title_phrase:"move_threads_ginlinemod",error_phrase:"error_moving_threads",success:function(c){a.cookie(k,null,{path:pageData.cookie_path,domain:pageData.cookie_domain});vBulletin.alert(movephrase,"inline_moved","",function(){location.reload()})}})}});vBulletin.AJAX({call:"/ajax/render/inlinemod_move_form",data:{postcount:c.length,moveposts:1,removeposts:1,firstpost:1,isAjaxTemplateRenderWithData:1},title_phrase:"move_threads_ginlinemod",error_phrase:"error_loading_move_form",
success:function(c){var b=a(".dialog-content .message",d);b.html(c.template);b.trigger("vb-instrument");d.dialog("option","position",{of:window});a("select",d).selectBox()}})}};vBulletin.inlinemod.movePosts=function(){var c=this,d=m(a(c));if(0==d.length)n("move_posts");else{var e=openConfirmDialog({title:vBulletin.phrase.get("move_posts"),message:vBulletin.phrase.get("loading")+"...",width:500,dialogClass:"inlinemod-moveposts-dialog loading",buttonLabel:{yesLabel:vBulletin.phrase.get("move_posts"),
noLabel:vBulletin.phrase.get("cancel")},onClickYes:function(){var b=e.find(".move-posts-form"),f=b.find("input:radio[name=type]:checked").val()||0;b={newtitle:b.find(':input[name="title"]').val(),to_parent:0==f?b.find(':input[name="destchannelid"]').val():b.find(':input[name="mergethreadurl"]').val().replace(pageData.baseurl+"/",""),nodeids:d,makeTopic:!0};vBulletin.AJAX({call:"/ajax/api/node/moveNodes",cpaction:!0,data:b,title_phrase:"move_posts",error_phrase:"error_moving_posts",success:function(b){a.cookie(k,
null,{path:pageData.cookie_path,domain:pageData.cookie_domain});if("thread"==l)-1!=a.inArray(a(c).attr("data-node-id"),b)||-1!=a.inArray(pageData.nodeid,b)?location.replace(a("#breadcrumbs .crumb a:last").attr("href")):a("input.cb_inlinemod[type=checkbox]:checked",g).each(function(){-1!=a.inArray(a(this).val(),b)&&a(this).parents(".inlinemod-item").remove()});else{var d=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance");d&&"function"==typeof d.applyFilters&&d.forceApplyFilters()}vBulletin.AJAX({call:"/ajax/api/route/getNodeUrl",
data:{nodeid:b[0]},success:function(a){location.href=pageData.baseurl+a}})}})}});vBulletin.AJAX({call:"/ajax/render/inlinemod_movePosts",data:{postcount:d.length,deleteposts:1,removeposts:1,firstpost:1},title_phrase:"move_posts",error_phrase:"error_loading_move_form",success:function(b){a(".inlinemod-moveposts-dialog").removeClass("loading");a(".dialog-content .message",e).html(b);e.dialog("option","position",{of:window});a("select",e).selectBox()}})}};vBulletin.inlinemod.stickThreads=function(c){var d=
this,e=m(a(d));c||(c="stick");if(0==e.length)n(c+"_threads");else return vBulletin.AJAX({call:"/ajax/api/node/setSticky",cpaction:!0,data:{nodeids:e,stick:"stick"==c?1:0},title_phrase:c+"_threads",error_phrase:"error_sticking_topics",success:function(b){vBulletin.inlinemod.clear.apply(d);"thread"==l?("stick"==c?(a(".canvas-widget").addClass("sticky"),b=vBulletin.phrase.get("this_topic_has_been_stuck")):(a(".canvas-widget").removeClass("sticky"),b=vBulletin.phrase.get("this_topic_has_been_successfully_unstuck")),
showStatusMessage(b,"stick")):(b=a(".filter-wrapper",a(d).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof b.applyFilters&&("topic"==l&&b.updatePageNumber(1),b.forceApplyFilters())}}),!1};vBulletin.inlinemod.unstickThreads=function(){return vBulletin.inlinemod.stickThreads.apply(this,["unstick"])};vBulletin.inlinemod.openCloseThreads=function(c){var d=this,e=m(a(d));c||(c="open");if(0==e.length)return n(c+"_threads"),!1;vBulletin.AJAX({call:"/ajax/api/node/"+c+"Node",
cpaction:!0,data:{nodeid:e},title_phrase:c+"_threads",error_phrase:"error_open_close_topic",success:function(b){vBulletin.inlinemod.clear.apply(d);"thread"==l?(b=a(".canvas-widget"),"open"==c?(b.removeClass("showclosed"),"0"==a(".canvas-widget #canmoderate").val()&&b.removeClass("closed_content-entry-box"),b=vBulletin.phrase.get("this_topic_has_been_successfully_opened")):(b.addClass("showclosed"),"0"==a(".canvas-widget #canmoderate").val()&&b.addClass("closed_content-entry-box"),b=vBulletin.phrase.get("this_topic_is_closed")),
showStatusMessage(b,"close")):(b=a(".filter-wrapper",a(d).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof b.applyFilters&&b.forceApplyFilters()}});return!1};vBulletin.inlinemod.approvePosts=function(a){return u(this,!0,a)};vBulletin.inlinemod.approveThreads=function(a){return u(this,!1,a)};vBulletin.inlinemod.changeAnswer=function(c){var d=a(this),e=m(d),b=d.data("starter")||0,f="set"==c,h=c+"asanswer",q="setAsAnswer",g={};c||(c="approve");if("remove"!=c){if(0==e.length||
1<e.length||e[0]==b){vBulletin.warning(h,"setasanswer_onlyone");return}g={nodeid:e[0],set:f?1:0}}else q="removeAnswers",g={nodeids:e};vBulletin.AJAX({call:"/ajax/api/node/"+q,cpaction:!0,data:g,title_phrase:h,error_phrase:"error_setasanswer",success:function(b){vBulletin.inlinemod.clear.apply(d[0]);if(b)if(showStatusMessage(vBulletin.phrase.get(f?"setasanswer_success":"unsetasanswer_success"),"setasanswer"),"thread"==l)if("remove"==c){let b=a(".js-post.pinned-answer");b.hide("slow",()=>{b.remove()});
a(".js-post.isanswer").toggleClass("isanswer",!1)}else e.forEach(b=>{a('li.js-post[data-node-id="'+b+'"]').toggleClass("isanswer",f)});else v(d[0]);else vBulletin.warning(h,"nothing_to_do")}});return!1};vBulletin.inlinemod.unfeatureThreads=function(){vBulletin.inlinemod.featureThreads.apply(this,["unfeature"])};vBulletin.inlinemod.featureThreads=function(c){var d=this,e=m(a(d));c||(c="feature");if(0==e.length)n(c+"_threads");else return vBulletin.AJAX({call:"/ajax/api/node/setFeatured",cpaction:!0,
data:{nodeids:e,set:"feature"==c?1:0},title_phrase:c+"_threads",error_phrase:"error_featuring_topics",success:function(b){vBulletin.inlinemod.clear.apply(d);if("thread"==l){if("feature"==c){-1!=a.inArray(a(d).attr("data-node-id"),b)&&a(".canvas-widget").addClass("featured");a(".inlinemod-item .cb_inlinemod",g).each(function(){-1!=a.inArray(this.value,b)&&a(this).closest(".list-item").removeClass("unfeatured")});var e=vBulletin.phrase.get("this_topic_has_been_featured")}else-1!=a.inArray(a(d).attr("data-node-id"),
b)&&a(".canvas-widget").removeClass("featured"),a(".inlinemod-item .cb_inlinemod",g).each(function(){-1!=a.inArray(this.value,b)&&a(this).closest(".list-item").addClass("unfeatured")}),e=vBulletin.phrase.get("this_topic_has_been_unfeatured");showStatusMessage(e,"feature")}else(e=a(".filter-wrapper",a(d).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof e.applyFilters&&e.forceApplyFilters()}}),!1};vBulletin.inlinemod.undelete=function(){var c=this,d=m(a(c));if(0==d.length)n("undelete_threads");
else return vBulletin.AJAX({call:"/ajax/api/node/undeleteNodes",cpaction:!0,data:{nodeids:d},title_phrase:"undelete_threads",error_phrase:"error_undeleting_topics",success:function(d){vBulletin.inlinemod.clear.apply(c);if("thread"==l){-1!=a.inArray(a(c).attr("data-node-id"),d)&&a(".conversation-content-widget").removeClass("deleted");a(".inlinemod-item .cb_inlinemod",g).each(function(){-1!=a.inArray(this.value,d)&&a(this).closest(".js-post").removeClass("deleted b-post--deleted")});var b=vBulletin.phrase.get("this_topic_is_undeleted");
showStatusMessage(b,"delete")}else(b=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof b.applyFilters&&b.forceApplyFilters()}}),!1};vBulletin.inlinemod.unapprovePosts=function(){return vBulletin.inlinemod.approvePosts.apply(this,["unapprove"])};vBulletin.inlinemod.unapproveThreads=function(){return vBulletin.inlinemod.approveThreads.apply(this,["unapprove"])};vBulletin.inlinemod.viewSelectedPosts=function(){0<p().length?window.location=pageData.baseurl+
"/search?cookie="+k:vBulletin.error("inline_mod","nothing_to_view")};vBulletin.inlinemod.mergePosts=function(){var c=this,d=m(a(c));if(2>d.length)vBulletin.warning("merge_posts","please_select_at_least_two_posts");else{var e=openConfirmDialog({title:vBulletin.phrase.get("merge_posts"),message:vBulletin.phrase.get("loading")+"...",width:600,dialogClass:"inlinemod-mergeposts-dialog loading",buttonLabel:{yesLabel:vBulletin.phrase.get("merge_posts"),noLabel:vBulletin.phrase.get("cancel")},onClickYes:function(){var b=
e.find("#hiddenVar_mergePosts").closest("form");b.find("[name=securitytoken]").remove();var d=b.serializeArray();d.push({name:"destnodeid",value:e.find(':input[name="destnodeid"]').val()});d.push({name:"destauthorid",value:e.find(':input[name="destauthorid"]').val()});d.push({name:"contenttype",value:b.attr("data-content-type")});vBulletin.AJAX({call:"/ajax/api/node/mergePosts",cpaction:!0,data:{input:d},title_phrase:"merge_posts",error_phrase:"error_merging_posts",success:function(b){a.cookie(k,
null,{path:pageData.cookie_path,domain:pageData.cookie_domain});(b=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof b.applyFilters?b.forceApplyFilters():location.reload()}})}});vBulletin.AJAX({call:"/ajax/render/inlinemod_mergePosts",data:{posts:d.join(","),postcount:d.length},title_phrase:"merge_posts",error_phrase:"error_loading_merge_form",success:function(b){a(".inlinemod-mergeposts-dialog").removeClass("loading");a(".dialog-content .message",
e).html(b);e.dialog("option","position",{of:window});a("select",e).selectBox();vBulletin.contentEntryBox.init();b=a(".js-content-entry form",e).data("content-type");a("body").trigger(b+"_editform_onload",[e,function(){}])}})}};vBulletin.inlinemod.copyPosts=function(){var c=this,d=m(a(c));if(0==d.length)n("copy_posts");else{var e=openConfirmDialog({title:vBulletin.phrase.get("copy_posts"),message:vBulletin.phrase.get("loading")+"...",width:500,dialogClass:"inlinemod-copyposts-dialog loading",buttonLabel:{yesLabel:vBulletin.phrase.get("copy_posts"),
noLabel:vBulletin.phrase.get("cancel")},onClickYes:function(){var b=e.find(".copy-posts-form"),f=b.find("input:radio[name=type]:checked").val()||0;f={newtitle:b.find(':input[name="title"]').val(),to_parent:0==f?b.find(':input[name="destchannelid"]').val():b.find(':input[name="mergethreadurl"]').val().replace(pageData.baseurl+"/",""),nodeids:d};vBulletin.AJAX({url:vBulletin.normalizeAjaxUrl(b.attr("action")),cpaction:!0,data:f,type:b.attr("method"),title_phrase:"copy_posts",error_phrase:"error_copying_posts",
success:function(b){a.cookie(k,null,{path:pageData.cookie_path,domain:pageData.cookie_domain});if("thread"==l){if(a.isPlainObject(b)){var d=0;a.each(b,function(b,c){if(a(".js-post[data-node-id={0}]".format(b)).hasClass("js-conversation-starter"))return d=c,!1});d||a.each(b,function(a,b){d=b;return!1});vBulletin.AJAX({call:"/ajax/api/route/getNodeUrl",data:{nodeid:d},success:function(a){location.href=pageData.baseurl+a}})}}else(b=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance"))&&
"function"==typeof b.applyFilters?b.forceApplyFilters():location.reload()}})}});vBulletin.AJAX({call:"/ajax/render/inlinemod_copyPosts",data:{postcount:d.length,deleteposts:1,removeposts:1,firstpost:1},title_phrase:"copy_posts",error_phrase:"error_loading_copy_posts_form",success:function(b){a(".inlinemod-copyposts-dialog").removeClass("loading");a(".dialog-content .message",e).html(b);e.dialog("option","position",{of:window});a("select",e).selectBox()}})}};vBulletin.inlinemod.mergeThreads=function(){var c=
this,d=p();if(2>d.length)vBulletin.warning("merge_threads_ginlinemod",1==d.length?"not_much_would_be_accomplished_by_merging":"you_did_not_select_any_valid_threads");else{var e=openConfirmDialog({title:vBulletin.phrase.get("merge_threads_ginlinemod"),message:vBulletin.phrase.get("loading")+"...",width:500,dialogClass:"inlinemod-merge-dialog loading",buttonLabel:{yesLabel:vBulletin.phrase.get("merge_threads_ginlinemod"),noLabel:vBulletin.phrase.get("cancel")},onClickYes:function(){var b=e.find(".merge-threads-form"),
f={};b.find("input[name=enableredirect]").prop("checked")&&(f.redirect=b.find("#rb_redirect_perm").prop("checked")?"perm":"expires","expires"==f.redirect&&(f.period=b.find("select[name=period]").val(),f.frame=b.find("select[name=frame]").val()),console.log("Redirect data compiled:"),console.dir(f));f={targetnodeid:b.find('select[name="targetnodeid"]').val(),nodeids:d,leaveRedirectData:f};vBulletin.AJAX({url:vBulletin.normalizeAjaxUrl(b.attr("action")),cpaction:!0,data:f,type:b.attr("method"),title_phrase:"merge_threads_ginlinemod",
error_phrase:"error_merging_threads",success:function(b){a.cookie(k,null,{path:pageData.cookie_path,domain:pageData.cookie_domain});(b=a(".filter-wrapper",a(c).parents(".conversation-toolbar")).data("object-instance"))&&"function"==typeof b.applyFilters?b.forceApplyFilters():location.reload()}})}});vBulletin.AJAX({call:"/ajax/render/inlinemod_mergeThreads",data:{postcount:d.length,nodeids:d},success:function(b){a(".inlinemod-merge-dialog").removeClass("loading");a(".dialog-content .message",e).html(b);
e.dialog("option","position",{of:window});a("select",e).selectBox()}})}};vBulletin.inlinemod.manage_deleted_form=function(c){function d(){var b=a(".manage-deleted-form"),c=a(".manage-deleted-form input:radio[name=deletetype]:checked").val();c&&(a("input:checkbox[name=keep_attachments]",b).prop("disabled",1!=c),a("input:checkbox[name=topicopen]",b).prop("disabled",2!=c),a("input:checkbox[name=topicsticky]",b).prop("disabled",2!=c),a("input:checkbox[name=topicvisible]",b).prop("disabled",2!=c));b.find("select.prefixid").selectBox()}
var e=a(this),b=c?c:e.parents(".js-post").attr("data-node-id"),f=openConfirmDialog({title:c?vBulletin.phrase.get("manage_content"):vBulletin.phrase.get("manage_deleted"),message:vBulletin.phrase.get("loading")+"...",width:510,dialogClass:"inlinemod-delete-dialog loading",buttonLabel:{yesLabel:vBulletin.phrase.get("save"),noLabel:vBulletin.phrase.get("cancel")},onClickYes:function(){var c=f.find(".manage-deleted-form");vBulletin.AJAX({url:vBulletin.normalizeAjaxUrl(c.attr("action")),cpaction:!0,data:{nodeid:b,
params:{deletetype:c.find("input:radio[name=deletetype]:checked").val()||0,reason:c.find(":input[name=deletereason]").val(),prefixid:c.find("select[name=prefixid]").val()||0,topictitle:c.find("input:text[name=topic_title]").val()||"",moderator_notes:c.find("textarea[name=moderator_notes]").val()||"",post_icon:c.find("input:radio[name=iconid]:checked").val()||0,keep_attachments:c.find("input:checkbox[name=keep_attachments]:checked").val()?1:0,option_open:c.find("input:checkbox[name=topicopen]:checked").val()?
1:0,option_sticky:c.find("input:checkbox[name=topicsticky]:checked").val()?1:0,option_visible:c.find("input:checkbox[name=topicvisible]:checked").val()?1:0}},success:function(b){a.cookie(k,null,{path:pageData.cookie_path,domain:pageData.cookie_domain});(b=a(".conversation-toolbar .filter-wrapper",a(e).parents(".inlinemod-container")).data("object-instance"))&&"function"==typeof b.applyFilters?b.forceApplyFilters():location.reload()},title_phrase:"error",error_phrase:"error_moderating_post"})}});vBulletin.AJAX({call:"/ajax/render/inlinemod_manage_deleted",
data:{nodeid:b,isblogcomment:1==e.parents(".js-comments--blog").length?1:0,isarticlecomment:1==e.parents(".js-comments--article").length?1:0,isAjaxTemplateRenderWithData:1},success:function(b){a(".inlinemod-delete-dialog").removeClass("loading");a(".dialog-content .message",f).html(b.template);f.dialog("option","position",{of:window});a(document).off("click",".manage-deleted-form input:radio[name=deletetype]").on("click",".manage-deleted-form input:radio[name=deletetype]",d);d()}})};vBulletin.inlinemod.editTopic=
function(){var c=a(this).attr("data-node-id");vBulletin.inlinemod.manage_deleted_form(c)};vBulletin.inlinemod.removeRedirect=function(){var c=a(this).attr("data-node-id");vBulletin.AJAX({call:"/ajax/api/content_redirect/removeRedirectsFromNode",data:{nodeid:c},success:function(a){vBulletin.alert("remove_redirects","thread_redirects_removed")}})};vBulletin.inlinemod.selectAll=function(){x(a(this),!0,"")};vBulletin.inlinemod.selectNone=function(){vBulletin.inlinemod.clear.apply(this)};vBulletin.inlinemod.selectClass=
function(c){x(a(this),!0,"."+c)};vBulletin.inlinemod.invertSelection=function(){a(".inlinemod-item .cb_inlinemod",a(this).parents(".inlinemod-container")).each(function(){var c=a(this);c.prop("checked",!c.prop("checked"));r(c)})};vBulletin.inlinemod.clear=function(){var c=a(this).parents(".inlinemod-container");a(".inlinemod-item .cb_inlinemod:checked",c).each(function(){a(this).prop("checked",!1).closest(".inlinemod-item").removeClass("inlinemod_highlight")});a(".cb_inlinemod_main",c).prop("checked",
!1);a.cookie(k,null,{path:pageData.cookie_path,domain:pageData.cookie_domain})};var x=function(c,d,e){a(".inlinemod-item"+e+" .cb_inlinemod",c.parents(".inlinemod-container")).each(function(){var b=a(this);b.prop("checked",d);r(b)})},r=function(c){var d=c.val(),e=p();if(c.prop("checked"))c.closest(".inlinemod-item").addClass("inlinemod_highlight"),-1==a.inArray(d,e)&&e.push(d),d=a(".inlinemod-item .cb_inlinemod",g),d.length==d.filter(":checked").length&&a(".cb_inlinemod_main",g).prop("checked",!0);
else{c.closest(".inlinemod-item").removeClass("inlinemod_highlight");c=[];for(var b=0;b<e.length;b++)e[b]!=d&&c.push(e[b]);e=c;a(".cb_inlinemod_main",g).prop("checked",!1)}cookie_str=e.join(",");a.cookie(k,cookie_str,{path:pageData.cookie_path,domain:pageData.cookie_domain})};vBulletin.inlinemod.markRead=function(){var c=a(this).closest(".channel-content-widget").attr("data-node-id");vBulletin.markchannelsread(c,{success:function(){location.reload()}})};vBulletin.inlinemod.init=function(c){c=c instanceof
a?c:a(c);0==c.length&&(c=a("body"));g=c.hasClass("inlinemod-container")?c:a(".inlinemod-container",c);l=a(".moderationmenu_container",g).attr("data-view");k=pageData.cookie_prefix+pageData.inlinemod_cookie_name+"_"+l;var d=p();if(0<d.length){var e=0;c=a(".inlinemod-item .cb_inlinemod",g).each(function(){-1!=a.inArray(this.value,d)&&(e++,a(this).prop("checked",!0),a(this).closest(".inlinemod-item").addClass("inlinemod_highlight"))});a(".cb_inlinemod_main",g).prop("checked",0<e&&e==c.length)}w(g);a(document).on("vb-loadnewposts",
function(a,c){w(c.insertedHtml)})};var k,l,g;a(document).ready(function(){g=a(".inlinemod-container");k||(g.is(":visible")?vBulletin.inlinemod.init(g):k=pageData.cookie_prefix+pageData.inlinemod_cookie_name);a(".inlinemod-container .cb_inlinemod_main").off("click mouseover").on("click",function(){vBulletin.inlinemod[this.checked?"selectAll":"selectNone"].apply(this)}).on("mouseover",function(){this.title=this.checked?a(this).attr("data-title-unselect"):a(this).attr("data-title-select")});a(".inlinemod-container").off("click",
".inlinemod-item input.cb_inlinemod").on("click",".inlinemod-item input.cb_inlinemod",function(c){r(a(this))});a(".moderationmenu_container .moderation-action a[data-action], .js-markread").off("click").on("click",function(c){c.stopPropagation();a(this).closest(".js-comp-menu-dropdown").removeClass("b-comp-menu-dropdown--open");var d=a(this).attr("data-action");if(!d)return console.warn("Unable to find the inline moderation function name."),!1;c=vBulletin.inlinemod[d];"function"==typeof c?(d=(d=a(this).attr("data-params"))?
d.split(","):[],c.apply(this,d)):console.warn('Unable to find the inline moderation function "{0}". Please ensure that it is defined in inlinemod.js.'.format("vBulletin.inlinemod."+d));return!1});a(".conversation-content-widget").off("click",".conversation-status-message .close").on("click",".conversation-status-message .close",function(){a(this).parent().fadeOut("slow")});return!1})})(jQuery);
