/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 5.7.4
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2023 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
(function(f){function m(a){a=f(".pagenav-form");var b=a.get(0),c=f(this).data("page");a.find(".js-pagenum").val(c);e.call(b,c);return!1}function g(a,b){b=b.find(".js-toolbar-pagenav");b.find(".js-pagenum").val(a);b.find(".left-arrow, .right-arrow").removeClass("h-disabled");1>=a&&b.find(".left-arrow").addClass("h-disabled");var c=b.find(".pagetotal").text();a>=c&&b.find(".right-arrow").addClass("h-disabled")}function l(a,b,c){c.find(".js-sort-by").removeClass("selected").find(".vb-icon").removeClass("vb-icon-triangle-up-wide vb-icon-triangle-down-wide").end().filter("[data-sortby={0}]".format(a)).addClass("selected").find(".vb-icon").addClass("vb-icon-triangle-{0}-wide".format("asc"==
b?"up":"down"));a=c.find(".js-memberlist-sortby-option").closest(".b-comp-menu-dropdown__content-item").removeClass("b-comp-menu-dropdown__content-item--current").end().filter("[data-sortby={0}][data-sortorder={1}]".format(a,b)).closest(".b-comp-menu-dropdown__content-item").addClass("b-comp-menu-dropdown__content-item--current");a.closest(".js-comp-menu-dropdown").find(".js-comp-menu-dropdown__trigger-text").text(a.text())}function h(a,b){a=a.toLowerCase();var c=b.find(".js-memberlist__letterfilter .letter");
c.removeClass("selected");b.find(".js-drop-down-startswith").val("").filter(".selectBox").selectBox("value","");if(""!==a){var d=a;"#"==a&&(d="numbers");c.filter(".js-letter-"+d).addClass("selected");b.find(".js-drop-down-startswith").val(d).filter(".selectBox").selectBox("value",d);b.find(".js-memberlist__usernamesearch").val("")}}function e(a){var b=f(this),c=b.closest(".js-memberlist-widget"),d={},e=c.data("hide-reputation");d.perpage=c.find(".js-per-page").data("perpage");b.hasClass("pagenav-form")||
(a=c.find(".toolbar-pagenav .js-pagenum").val());d.pagenumber=a;a=a=>a.is(".js-letter-all")?"":a.html()||"";b.hasClass("js-drop-down-startswith")?(delete d.pagenumber,a=c.find(".js-drop-down-startswith").val(),h(a,c),g(1,c)):b.hasClass("letter")?(delete d.pagenumber,a=a(b),h(a,c),g(1,c)):a=a(c.find(".js-memberlist__letterfilter .js-letter.selected"));a&&(a=a.toLowerCase(),"all"===a&&(a=""),"numbers"===a&&(a="#"),a.length&&(d.startswith=a));b.is(".js-memberlist__usernamesearch")?(delete d.pagenumber,
d.startswith&&delete d.startswith,a=b.val(),""!==a?(d.username=a,h("",c)):h("all",c),c.find(".js-memberlist__usernamesearch").val(a),g(1,c)):(a=c.find(".js-memberlist__usernamesearch").val(),""!==a&&(d.username=a));if(b.hasClass("js-memberlist-sortby-option"))delete d.pagenumber,a=b.data("sortby"),b=b.data("sortorder"),l(a,b,c),g(1,c);else if(b.hasClass("js-sort-label")){delete d.pagenumber;var k=b.parents(".js-sort-by");a=k.data("sortby");b=k.data("sortorder");k.hasClass("selected")&&(b="asc"==b?
"desc":"asc",k.data("sortorder",b));l(a,b,c);g(1,c)}else b=c.find(".js-sort-by.selected"),a=b.data("sortby"),b=b.data("sortorder");d.sortfield=a;d.sortorder=b;b=c.find(".js-memberlist-route-info").data("routeinfojson");vBulletin.AJAX({call:"/ajax/render/memberlist_items",data:{criteria:d,routeInfoJson:b,hide_reputation:e},success:function(a){c.find(".js-memberlist-table-body").replaceWith(a);a=c.find(".js-memberlist-table-body");var b=a.data("totalPages"),d=a.find(".js-pagenav-current-button").data("page")||
1,e=c.find(".js-toolbar-pagenav"),h=e.find(".js-pagenum").val(),k=e.find(".right-arrow");e.find(".pagetotal").text(b);k.addClass("h-disabled");h<b&&e.find(".right-arrow").removeClass("h-disabled");g(d,c);a=a.find(".js-pagenav").clone();c.find(".js-under-toolbar-pagenav .js-pagenav").replaceWith(a);vBulletin.Responsive.Debounce.checkShrinkEvent(f(".js-pagenav"))}});return!1}f(function(){vBulletin.pagination({context:".memberlist-widget .conversation-toolbar",onPageChanged:e});var a=f(".js-drop-down-startswith");
if(a.is(":visible"))a.selectBox().change(e);else{var b=a.closest(".h-hide-on-large");b.removeClass("h-hide-on-large");a.selectBox().change(e);b.addClass("h-hide-on-large")}a=f(".memberlist-widget");a.offon("click.memberlist",".js-memberlist__letterfilter .letter",e);a.offon("click.memberlist",".js-sort-label",e);a.offon("click.memberlist",".js-memberlist-sortby-option",e);a.offon("click.memberlist",".js-pagenav .js-pagenav-button",m);f(".js-memberlist__usernamesearch").offon("keyup.memberlist",f.debounce(400,
e))})})(jQuery);
