/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 5.7.4
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2023 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache(["error","showing_x_to_y_of_z_users","x_members_y_guests_online"],[]);
(function(b){if(!vBulletin.pageHasSelectors([".wollist-widget"]))return!1;b(function(){function m(){b(".js-wol-username").each(function(){var a=b(this),c=a.parent().find(".js-wol-userinfo-tooltip");vBulletin.isRtl();c.length&&vBulletin.qtip.apply(a,"qtip-topicpreview",{content:c})})}function n(){b(document).off("click",".js-pagenav .js-pagenav-button").on("click",".js-pagenav .js-pagenav-button",function(a){var c=b(this);a=c.closest(".wollist-widget").data("widget-instance-id");c=c.data("page");var e=
b(".pagenav-form");k.updatePageNavigation(e,c);g(a);return!1})}function g(a,c){var e=b('div.wollist-widget[data-widget-instance-id="'+a+'"]'),g=b('.pagenav-controls :input[name="page"]',e).val(),f=b(".widget-content",e),l=f.data("perpage");a=f.data("thispageonly");var k=f.data("pagekey"),d=f.data("who"),h=f.data("resolve");f=f.data("pagerouteid");d={who:d,pagenumber:g,perpage:l,resolveIp:h,pageRouteId:f};"object"==typeof c?(d.sortfield=c.sortby,d.sortorder=c.sortorder):(h=b(".js-wol-sort-by").filter(function(){return b(this).find(".js-sort-arrow").is(".vb-icon-triangle-up-wide, .vb-icon-triangle-down-wide")}),
d.sortfield=h.data("sortby"),d.sortorder=h.data("sortorder"));"1"==a&&(d.pagekey=k);b("body").css("cursor","wait");vBulletin.AJAX({call:"/ajax/api/wol/refreshUsers",data:d,complete:function(c,a){console.log("wol-refreshUsers complete.");b("body").css("cursor","auto")},success:function(a,f,d){f=(g-1)*l+1;d=g*l;d=d>a.userCounts.total?a.userCounts.total:d;var h=b(".js-wol-sort-by");"undefined"!=typeof c&&(h.find(".js-sort-arrow").removeClass("vb-icon-triangle-up-wide vb-icon-triangle-down-wide"),h.each(function(){var a=
b(this);a.data("sortby")==c.sortby?a.find(".js-sort-arrow").addClass("asc"==c.sortorder?"vb-icon-triangle-up-wide":"vb-icon-triangle-down-wide"):a.data("sortorder","desc")}));b(".widget-content .js-table-content",e).empty().html(a.template);b(".widget-content .user-counters",e).html(vBulletin.phrase.get("showing_x_to_y_of_z_users",f,d,a.userCounts.total));b(".widget-content .user-counts",e).html(vBulletin.phrase.get("x_members_y_guests_online",a.userCounts.members,a.userCounts.guests));m();n()},title_phrase:"online_users",
error_phrase:"error_fetching_online_users"})}var k=new vBulletin.pagination({context:b(".wollist-widget"),onPageChanged:function(a,c){a=b(this).closest(".wollist-widget").data("widget-instance-id");g(a)}});b(".wollist-widget").each(function(){var a=b(this).attr("data-widget-instance-id"),c=parseInt(b(".widget-content",b(this)).attr("data-refresh"));0<c&&window.setInterval(function(){g(a)},1E3*c)});b(document).off("click",".js-wol-sort-by").on("click",".js-wol-sort-by",function(a){a=b(this);var c=
a.closest(".wollist-widget").attr("data-widget-instance-id"),e=a.data("sortorder");e={sortby:a.data("sortby"),sortorder:"desc"==e?"asc":"desc"};a.data("sortorder",e.sortorder);g(c,e)});b(document).off("click",".resolveIpLink").on("click",".resolveIpLink",function(a){a.preventDefault();var c=b(this);vBulletin.AJAX({call:"/ajax/call/bbcode/resolveIp",data:{ip:c.text()},success:function(a){c.replaceWith(a)},complete:function(){b("body").css("cursor","default")}})});m();n()})})(jQuery);
