/*
 =======================================================================*\
|| ###################################################################### ||
|| # vBulletin 5.7.4
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2023 MH Sub I, LLC dba vBulletin. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
vBulletin.precache("following following_pending following_remove showing_x_subscribers showing_x_subscriptions unable_to_contact_server_please_try_again".split(" "),[]);
(function(b){if(!vBulletin.pageHasSelectors([".subscriptions-widget"]))return!1;b(function(){var n=vBulletin.tabtools,h=b(".subscriptions-widget .subscribeTabs");b(".subscriptions-tab, .subscription-list",h);var l={},g,k;b(".ui-tabs-nav > li",h).removeClass("ui-state-disabled");var e=h.find(".ui-tabs-nav > li");var m=e.filter(".ui-tabs-active");var t=m.index();$defaultTabAnchor=m.find("> a");var p=$defaultTabAnchor.data("url-path");allowTabHistory="1"==e.parent().data("allow-history");tabHistory=
new vBulletin.history.instance(allowTabHistory);var q=function(a,c,d,f,e,u,g){return n.newTab(a,c,f,e,u,null,g,b.noop,d)},r=function(a,c){c=b(".subscription-list-header .last-activity .arrow .vb-icon",c);a=a.isFilterSelected("mostactive");c.toggleClass("vb-icon-triangle-down-wide",a).toggleClass("vb-icon-triangle-up-wide",!a)};n.initTabs(h,tabHistory,e,allowTabHistory,t,p,[g],!1,function(a,c,d){var f=b(d);a="#"+f.prop("id");c=p==b(c).data("url-path");a in l||(l[a]=n.tabAllowHistory(f));"#subscriptionsTab"==
a?(g||(subscriptionValues=q(f,void 0,l[a],!0,!1,c,function(){r(g,f)}),g=subscriptionValues.filter),g.applyFilters(!1,!1,!1,!0)):"#subscribersTab"==a&&(k||(subscriberValues=q(f,void 0,l[a],!0,!1,c,function(){r(k,f)}),k=subscriberValues.filter),k.applyFilters(!1,!1,!1,!0))});tabHistory.isEnabled()&&(e=tabHistory.getState(),m=vBulletin.parseQueryString(location.search,["_"]),0!=Object.keys(m).length||e&&!b.isEmptyObject(e.data)||(e=location.pathname.match(/\/(subscriptions|subscribers)\/?$/),e={from:"tabs",
tab:e&&e[1]||$defaultTabAnchor.data("url-path")},tabHistory.setDefaultState(e,document.title,location.href)));actionSubscribeButton=function(){var a=b(this),c=parseInt(a.attr("data-follow-id")),d=a.attr("data-type");if(("follow_members"==d||"follow_contents"==d)&&c){var f="";a.hasClass("add")?f="add":a.hasClass("delete")&&(f="delete");vBulletin.AJAX({call:"/profile/follow-button",data:{"do":f,follower:c,type:d},success:function(b){if(1==b||"1"==b){var c="b-button";if("delete"==f)if(a.attr("data-canusefriends")){c+=
" add subscribe_button b-button--secondary";var d="unsubscribe_button delete subscribed_button b-button--special";var e="follow"}else{a.remove();return}else c+=" delete subscribed_button b-button--special",d="add subscribe_button b-button--secondary",e="follow"}else 2==b&&(c="subscribe_pending secondary",d="b-button--special",e="following_pending");a.addClass(c).removeClass(d).find(".js-button__text-primary").text(vBulletin.phrase.get(e))},title_phrase:"following"})}};h.off("click",".js-subscription__follow").on("click",
".js-subscription__follow",actionSubscribeButton);b(".subscriptionsContainer").off("mouseenter mouseleave",".js-subscription__follow").on("mouseenter",".js-subscription__follow",function(){var a=b(this);!a.hasClass("subcribe_pending")&&a.hasClass("subscribed_button")&&a.data("hover-timer",setTimeout(function(){a.toggleClass("subscribed_button unsubscribe_button").toggleClass("b-button--special b-button--secondary").find(".js-button__text-primary").text(vBulletin.phrase.get("following_remove"))},100))}).on("mouseleave",
".js-subscription__follow",function(){var a=b(this);clearTimeout(a.data("hoverTimer"));!a.hasClass("subcribe_pending")&&a.hasClass("unsubscribe_button")&&a.toggleClass("subscribed_button unsubscribe_button").toggleClass("b-button--special b-button--secondary").find(".js-button__text-primary").text(vBulletin.phrase.get("following"))});b(document).off("click",".subscription-list-header .last-activity .arrow").on("click",".subscription-list-header .last-activity .arrow",function(){var a=b(".vb-icon",
this).hasClass("vb-icon-triangle-down-wide")?"leastactive":"mostactive",c=b(this).closest(".tab"),d="subscriptionsTab"==c.attr("id")?g:k;d.updatePageNumber(1);delete d.lastFilters;c.find(".conversation-toolbar-wrapper .toolbar-filter-overlay .filter-options input[name=filter_sort][value="+a+"]").prop("checked",!1).trigger("click")});b(document).off("click",".subscription-list-header .subscription-name .arrow").on("click",".subscription-list-header .subscription-name .arrow",function(){var a=b(".vb-icon",
this),c=a.hasClass("vb-icon-triangle-up-wide")?!0:!1,d=b(this).closest(".subscription-list-container").find(".subscription-list");$listitems=d.hasClass("js-subscribers-list")?d.find(".subscription-item .subscription-name .author"):d.find(".subscription-item .subscription-name a");$listitems.sort(function(a,d){if(c){var e=a;a=d;d=e}return b(a).text().toUpperCase().localeCompare(b(d).text().toUpperCase())});b.each($listitems,function(a,c){d.append(b(c).closest(".subscription-item"))});a.toggleClass("vb-icon-triangle-up-wide",
!c).toggleClass("vb-icon-triangle-down-wide",c)})})})(jQuery);
